### ISSUE TITLE
请问代码大概什么时候能可以开源

### ISSUE THREAD

**Issue by ruiqiyan** [gqk/HiCoM#1]

**Comment by gqk** [comment]
您好，感谢关注！代码预计在12月中旬前发布，我们现在已经把我们的代码库开源出来：[LibGS](https://github.com/Awesome3DGS/libgs)，您可以先看一下我们复现的几个方法，本工作的代码结构大致相同。

**Comment by ruiqiyan** [comment]
好的，谢谢您的分享。

**Comment by gqk** [comment]
@ruiqiyan 您好，

代码已经发布了，您可以参考README运行，如有问题，欢迎随时联系。

这个 issue 我就先 close 了，再次感谢您的关注！
